Repository Za-ply/Zaply-client, pull requests merged in 2025-05, with the labels that each got.

#12 feat(9): 회원가입 페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/assets/images/background2.webp
  public/assets/images/backgroundLine.webp
  public/assets/images/logo_color.webp
  public/sw.js
  public/sw.js.map
  public/workbox-8817a5e5.js
  public/workbox-8817a5e5.js.map
  public/workbox-e9849328.js
  src/app/(auth)/policy/_components/PolicyContainer.tsx
  src/app/(auth)/policy/_components/PolicyList.tsx
  src/app/(auth)/policy/_components/constants/index.ts
  src/app/(auth)/policy/_components/store/policy-store.ts
  src/app/(auth)/policy/page.tsx
  src/app/(auth)/sign-up-complete/_animation/index.ts
  src/app/(auth)/sign-up-complete/page.tsx
  src/app/(auth)/sign-up/_components/constants/index.ts
  src/app/(auth)/sign-up/_components/email/EmailCheckWrapper.tsx
  src/app/(auth)/sign-up/_components/email/EmailForm.tsx
  src/app/(auth)/sign-up/_components/hooks/useAutoFocus.ts
  src/app/(auth)/sign-up/_components/hooks/useFormatTime.ts
  src/app/(auth)/sign-up/_components/hooks/useTimer.ts
  src/app/(auth)/sign-up/_components/password/PasswordCheckWrapper.tsx
  src/app/(auth)/sign-up/_components/password/PasswordForm.tsx
  src/app/(auth)/sign-up/_components/userInfo/UserInfoForm.tsx
  src/app/(auth)/sign-up/_components/userInfo/UserInfoWrapper.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/button/index.tsx
  src/components/common/container/index.tsx
  src/components/common/input/index.tsx
  src/components/common/toast/toaster.tsx
  src/components/icons/index.ts
  src/components/icons/logo/index.tsx
  src/components/icons/service/index.tsx
  src/lib/axios/.gitkeep
  src/lib/zod/index.ts
  src/lib/zod/schema-email.ts
  src/lib/zod/schema-password.ts
  src/lib/zod/schema-userInfo.ts
  src/types/index.ts
  src/types/password.ts
  src/utils/useToast.ts
  tailwind.config.js
  tsconfig.json
Labels: 🌱 feature, 💄 design

#17 feat(16): 공통 모달 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/app/(modal)/test-modal/page.tsx
  src/app/@modal/(.)test-modal/page.tsx
  src/components/common/dialog/index.tsx
  src/components/common/modal/index.tsx
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#19 feat(18): BNB 컴포넌트 구현 및 TopBar 전환 애니메이션 추가
  src/app/page.tsx
  src/components/animation/index.ts
  src/components/common/bnb/index.tsx
  src/components/common/topBar/index.tsx
  src/components/icons/service/index.tsx
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#22 feat(20): api 기본 인스턴스 및 초기 구조 설정
  package.json
  pnpm-lock.yaml
  src/api/.gitkeep
  src/lib/api/axios/instance.ts
  src/lib/api/axios/tokenManager.ts
  src/lib/api/controller/AuthController.ts
  src/lib/api/controller/index.ts
  src/lib/api/model/auth.ts
  src/lib/api/model/index.ts
  src/lib/api/model/response.ts
  src/lib/api/service/AuthService.ts
  src/lib/api/service/index.ts
  src/lib/axios/.gitkeep
  src/providers/provider-query.tsx
Labels: 🌱 feature

#23 feat(21): 메인 페이지 상단 UI
  src/app/main/_components/content/MainContent.tsx
  src/app/main/_components/hooks/useFormatCount.ts
  src/app/main/_components/section/Chips.tsx
  src/app/main/_components/section/ContentButton.tsx
  src/app/main/_components/section/MainSection.tsx
  src/app/page.tsx
  src/components/icons/service/index.tsx
  src/types/chips.ts
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#26 feat(24): 메인 페이지 퍼블리싱
  public/assets/images/facebook-logo.svg
  public/assets/images/insta-logo.svg
  public/assets/images/threads-logo.svg
  public/sw.js
  src/app/(main)/main/_components/constants/chips.ts
  src/app/(main)/main/_components/content/ContentItem.tsx
  src/app/(main)/main/_components/content/ContentList.tsx
  src/app/(main)/main/_components/content/ContentToggle.tsx
  src/app/(main)/main/_components/content/MainContent.tsx
  src/app/(main)/main/_components/content/Platforms.tsx
  src/app/(main)/main/_components/hooks/useFormatCount.ts
  src/app/(main)/main/_components/hooks/useFormatTime.ts
  src/app/(main)/main/_components/mocks/contentItems.ts
  src/app/(main)/main/_components/section/Chips.tsx
  src/app/(main)/main/_components/section/ContentButton.tsx
  src/app/(main)/main/_components/section/MainSection.tsx
  src/app/main/_components/content/MainContent.tsx
  src/app/page.tsx
  src/components/common/bnb/index.tsx
  src/components/icons/service/index.tsx
  src/stores/useContentStore.ts
  src/types/chips.ts
  src/types/contentItem.ts
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#28 feat(27): 로그인, 회원가입 관련 API 연결
  package.json
  pnpm-lock.yaml
  src/app/(auth)/policy/_components/PolicyContainer.tsx
  src/app/(auth)/sign-in/_components/SignInForm.tsx
  src/app/(auth)/sign-up-complete/page.tsx
  src/app/(auth)/sign-up/_components/email/EmailCheckWrapper.tsx
  src/app/(auth)/sign-up/_components/password/PasswordCheckWrapper.tsx
  src/app/(auth)/sign-up/_components/userInfo/UserInfoForm.tsx
  src/app/(auth)/sign-up/_components/userInfo/UserInfoWrapper.tsx
  src/components/icons/service/index.tsx
  src/lib/api/axios/tokenManager.ts
  src/lib/api/controller/AuthController.ts
  src/lib/api/controller/SmsController.ts
  src/lib/api/model/sms.ts
  src/lib/api/service/AuthService.ts
  src/lib/api/service/SmsService.ts
  src/stores/useSignUpStore.ts
Labels: 🌱 feature

#37 feat(33): 마이페이지 메인, 연결 페이지 퍼블리싱
  public/assets/images/background_white.webp
  src/app/(auth)/sign-in/_components/SignInHeader.tsx
  src/app/(auth)/sign-up-complete/page.tsx
  src/app/(main)/main/_components/hooks/useLinkModalOnce.ts
  src/app/(main)/main/_components/section/ContentButton.tsx
  src/app/(main)/main/_components/section/MainSection.tsx
  src/app/(main)/main/page.tsx
  src/app/(modal)/link/page.tsx
  src/app/(mypage)/connect-complete/_components/CompleteContent.tsx
  src/app/(mypage)/connect-complete/_components/ErrorContent.tsx
  src/app/(mypage)/connect-complete/page.tsx
  src/app/(mypage)/connect/_components/ConnectSocialStep.tsx
  src/app/(mypage)/connect/_components/ProfileSelect.tsx
  src/app/(mypage)/connect/_components/ProfileSelectStep.tsx
  src/app/(mypage)/connect/_components/SocialSelect.tsx
  src/app/(mypage)/connect/_components/store/link-store.ts
  src/app/(mypage)/connect/_components/store/social-store.ts
  src/app/(mypage)/connect/page.tsx
  src/app/(mypage)/mypage/_components/MyPageHeader.tsx
  src/app/(mypage)/mypage/_components/MyPageList.tsx
  src/app/(mypage)/mypage/_components/SnsProfile.tsx
  src/app/(mypage)/mypage/_components/SocialCard.tsx
  src/app/(mypage)/mypage/page.tsx
  src/app/@modal/(.)link/page.tsx
  src/components/common/bnb/index.tsx
  src/components/common/bottomModal/index.tsx
  src/components/common/button/index.tsx
  src/components/common/index.ts
  src/components/common/topBar/index.tsx
  src/components/icons/logo/index.tsx
  src/components/icons/service/index.tsx
  src/stores/useContentStore.ts
  src/types/contentItem.ts
  src/utils/useFormatCount.ts
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#38 feat(35): 계정 관리 페이지 퍼블리싱 및 계정 연동 API
  public/assets/images/background_blue_green.webp
  public/sw.js
  src/app/(auth)/sign-in/page.tsx
  src/app/(main)/main/page.tsx
  src/app/(modal)/unLinkWarning/page.tsx
  src/app/(mypage)/_components/types/platform.ts
  src/app/(mypage)/connect-complete/_components/CompleteContent.tsx
  src/app/(mypage)/connect-complete/_components/ErrorContent.tsx
  src/app/(mypage)/connect/_components/ConnectSocialStep.tsx
  src/app/(mypage)/connect/_components/ProfileSelect.tsx
  src/app/(mypage)/connect/_components/ProfileSelectStep.tsx
  src/app/(mypage)/connect/_components/SocialLogin.tsx
  src/app/(mypage)/connect/_components/SocialSelect.tsx
  src/app/(mypage)/connect/_components/store/link-store.ts
  src/app/(mypage)/connect/_components/store/social-store.ts
  src/app/(mypage)/connect/page.tsx
  src/app/(mypage)/mypage/_components/SnsProfile.tsx
  src/app/(mypage)/mypage/_components/SocialCard.tsx
  src/app/(mypage)/socials/_components/InfoCard.tsx
  src/app/(mypage)/socials/_components/SocialList.tsx
  src/app/(mypage)/socials/_components/SocialUnLinked.tsx
  src/app/(mypage)/socials/_components/Update.tsx
  src/app/(mypage)/socials/_components/config/social-config.ts
  src/app/(mypage)/socials/_components/constants/socialInfo.ts
  src/app/(mypage)/socials/info/page.tsx
  src/app/(mypage)/socials/page.tsx
  src/app/(mypage)/socials/unlinked/page.tsx
  src/app/@modal/(.)unLinkWarning/page.tsx
  src/app/onboarding/_components/OnBoardingFooter.tsx
  src/app/onboarding/page.tsx
  src/components/common/bnb/index.tsx
  src/lib/api/controller/AccountController.ts
  src/lib/api/service/AccountService.ts
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#42 feat(41): 바텀 시트 모달 수정
  package.json
  pnpm-lock.yaml
  public/assets/images/background_green.webp
  public/assets/images/background_pink.webp
  public/assets/images/background_white.webp
  public/assets/images/background_yellow.webp
  public/sw.js
  src/app/(auth)/sign-in/_components/SignInForm.tsx
  src/app/(main)/main/(modal)/link/page.tsx
  src/app/(main)/main/@modal/(.)link/page.tsx
  src/app/(main)/main/@modal/default.tsx
  src/app/(main)/main/_components/content/MainContent.tsx
  src/app/(main)/main/_components/hooks/useLinkModalOnce.ts
  src/app/(main)/main/_components/section/MainSection.tsx
  src/app/(main)/main/layout.tsx
  src/app/(main)/main/page.tsx
  src/app/(main)/new-content/_components/common/InfoMainPlatform.tsx
  src/app/(main)/new-content/_components/config/constraint-config.ts
  src/app/(main)/new-content/_components/step/content-make/UploadFile.tsx
  src/app/(main)/new-content/_components/step/platform-select/BottomContent.tsx
  src/app/(main)/new-content/_components/step/platform-select/BottomSheet.tsx
  src/app/(mypage)/mypage/page.tsx
  src/app/(mypage)/socials/_components/InfoCard.tsx
  src/app/@modal/(.)warning/page.tsx
  src/components/common/bottomModal/index.tsx
  src/components/common/dialog/index.tsx
  src/components/common/index.ts
  src/components/common/modal/index.tsx
  src/components/common/vaul/index.tsx
  src/components/drawer/index.tsx
  src/utils/useScrollBlur.ts
  tailwind.config.js
Labels: 🌱 feature, 🛠️ fix

#44 feat(32): 스레드 연동, 연동 끊기, 연동 상태 조회, 정보 조회 API 연결 및 캘린더, 타임피커 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/sw.js
  src/app/(auth)/policy/_components/PolicyContainer.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/_components/password/PasswordCheckWrapper.tsx
  src/app/(auth)/sign-up/_components/userInfo/UserInfoWrapper.tsx
  src/app/(main)/main/_components/section/MainSection.tsx
  src/app/(main)/new-content/_components/step/reserve/ReserveStep.tsx
  src/app/(mypage)/connect-complete/_components/CompleteContent.tsx
  src/app/(mypage)/connect-complete/page.tsx
  src/app/(mypage)/connect/_components/ConnectSocialStep.tsx
  src/app/(mypage)/connect/_components/SocialLogin.tsx
  src/app/(mypage)/connect/_components/hooks/useAccounts.ts
  src/app/(mypage)/connect/_components/store/link-store.ts
  src/app/(mypage)/facebook/callback/page.tsx
  src/app/(mypage)/mypage/_components/MyPageHeader.tsx
  src/app/(mypage)/mypage/_components/SnsProfile.tsx
  src/app/(mypage)/mypage/_components/SocialCard.tsx
  src/app/(mypage)/socials/_components/InfoCard.tsx
  src/app/(mypage)/socials/_components/SocialList.tsx
  src/app/(mypage)/socials/_components/SocialUnLinked.tsx
  src/app/(mypage)/threads/callback/page.tsx
  src/app/@modal/(.)unLinkWarning/page.tsx
  src/components/common/button/index.tsx
  src/components/common/calendar/index.tsx
  src/components/common/timePicker/index.tsx
  src/lib/api/axios/instance.ts
  src/lib/api/controller/AccountController.ts
  src/lib/api/controller/AuthController.ts
  src/lib/api/controller/MemberController.ts
  src/lib/api/model/account.ts
  src/lib/api/model/auth.ts
  src/lib/api/model/index.ts
  src/lib/api/model/member.ts
  src/lib/api/service/AccountService.ts
  src/lib/api/service/AuthService.ts
  src/lib/api/service/MemberService.ts
  src/stores/memberStore.ts
  src/stores/userStore.ts
  tailwind.config.js
Labels: 🌱 feature, 💄 design

#48 feat(47): 라우트 프리패칭 훅 추가
  public/sw.js
  src/app/(main)/main/_components/section/MainSection.tsx
  src/app/onboarding/_components/OnBoardingContent.tsx
  src/utils/useRouterPrefetch.ts
Labels: 🌱 feature

#53 feat(52): 게시물 불러오기 api 연동
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/assets/images/blur.png
  public/assets/images/default.png
  public/sw.js
  src/app/(auth)/sign-up-complete/page.tsx
  src/app/(main)/[projectId]/new-content/_components/common/index.ts
  src/app/(main)/[projectId]/new-content/_components/content/InfoMainPlatform.tsx
  src/app/(main)/[projectId]/new-content/_components/content/LoadContentList.tsx
  src/app/(main)/[projectId]/new-content/_components/content/index.ts
  src/app/(main)/[projectId]/new-content/_components/hooks/useLoadContent.ts
  src/app/(main)/[projectId]/new-content/_components/mocks/index.ts
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/LoadContent.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/NoContentList.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/PostCard.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/ShowContentList.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/ShowDetailList.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/ViewFiter.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/PlatfomButton.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/Upload/UploadFile.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/WriteContent.tsx
  src/app/(main)/[projectId]/new-content/_components/step/platform-select/HeaderContent.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/SelectUploadType.tsx
  src/app/(main)/[projectId]/new-content/_components/store/post-store.ts
  src/app/(main)/main/_components/section/ContentButton.tsx
  src/app/(modal)/preparing/page.tsx
  src/app/@modal/(.)preparing/page.tsx
  src/app/@modal/(.)warning/page.tsx
  src/components/common/bnb/index.tsx
  src/components/common/dialog/index.tsx
  src/components/common/modal/index.tsx
  src/components/common/spinner/index.tsx
  src/components/drawer/index.tsx
  src/components/dropdown/index.tsx
  src/constants/query-keys.ts
  src/constants/search-options.ts
  src/hooks/query/usePosting.ts
  src/hooks/useInfiniteScroll.ts
  src/lib/api/controller/PostingController.ts
  src/lib/api/model/posting.ts
  src/lib/api/service/PostService.ts
  tailwind.config.js
Labels: 🌱 feature

#55 feat(50): 구글 로그인 연동 및 콘텐츠 예약 시간 수정 API 연결
  next.config.mjs
  public/assets/svgs/onboarding_image1.svg
  public/assets/svgs/onboarding_image2.svg
  public/assets/svgs/onboarding_image3.svg
  public/sw.js
  src/app/(auth)/google/callback/page.tsx
  src/app/(auth)/sign-in/_components/constants/onboardingContents.ts
  src/app/(main)/[projectId]/new-content/_components/step/content-make/PlatfomButton.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/ScheduleBlock.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/ScheduleSelector.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/SelectUploadType.tsx
  src/app/(main)/[projectId]/new-content/_components/store/reserve-store.ts
  src/app/(main)/main/_components/content/ContentItem.tsx
  src/app/(main)/main/_components/content/ContentList.tsx
  src/app/(main)/main/_components/content/ContentToggle.tsx
  src/app/(main)/main/_components/hooks/useFormatTime.ts
  src/app/(main)/main/_components/hooks/useProjects.ts
  src/app/(main)/main/page.tsx
  src/app/(main)/reserved-contents/[projectId]/page.tsx
  src/app/(main)/reserved-contents/[projectId]/update/page.tsx
  src/app/(main)/reserved-contents/_components/CollapsibleReservationContent.tsx
  src/app/(main)/reserved-contents/_components/CollapsibleReservationTime.tsx
  src/app/(main)/reserved-contents/_components/ReservedLists.tsx
  src/app/(main)/reserved-contents/_components/UpdateReservationContent.tsx
  src/app/(main)/reserved-contents/_components/UpdateTimeContent.tsx
  src/app/(main)/reserved-contents/_components/constants/platforms.ts
  src/app/(main)/reserved-contents/_components/hooks/usePostingInfo.ts
  src/app/(main)/reserved-contents/_components/hooks/useUpdateReservation.ts
  src/app/(main)/reserved-contents/_components/types/posting.ts
  src/app/(main)/reserved-contents/_components/utils/date.ts
  src/app/(main)/reserved-contents/page.tsx
  src/app/(mypage)/facebook/callback/page.tsx
  src/app/(mypage)/facebook/link/page.tsx
  src/app/(mypage)/mypage/_components/SnsProfile.tsx
  src/app/(mypage)/socials/_components/SocialUnLinked.tsx
  src/app/onboarding/_components/OnBoardingContent.tsx
  src/components/common/bnb/index.tsx
  src/components/drawer/index.tsx
  src/constants/query-keys.ts
  src/lib/api/controller/AccountController.ts
  src/lib/api/controller/AuthController.ts
  src/lib/api/controller/PostingController.ts
  src/lib/api/controller/ProjectController.ts
  src/lib/api/model/account.ts
  src/lib/api/model/auth.ts
  src/lib/api/model/index.ts
  src/lib/api/model/member.ts
  src/lib/api/model/posting.ts
  src/lib/api/model/project.ts
  src/lib/api/service/AuthService.ts
  src/lib/api/service/MemberService.ts
  src/lib/api/service/PostingService.ts
  src/lib/api/service/ProjectService.ts
  src/stores/useContentStore.ts
Labels: 🌱 feature, 💄 design

#62 fix(61): 각종 스타일 수정 및 오류 사항 수정
  src/app/(main)/[projectId]/new-content/_components/step/content-make/LoadContent/ShowContentList.tsx
  src/app/(main)/[projectId]/new-content/_components/step/content-make/PlatfomButton.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/ReserveStep.tsx
  src/app/(main)/[projectId]/new-content/_components/step/reserve/ScheduleSelector.tsx
  src/app/(main)/main/_components/section/ContentButton.tsx
  src/app/(main)/reserved-contents/_components/CollapsibleReservationTime.tsx
Labels: 🛠️ fix
